
target_include_directories(Pcynlitx PUBLIC

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/MainFrame

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_Close_Button

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_DataPanel

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_wxPanel

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_Notebook

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_TabArt

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_TextCtrl

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_Tree_View_Panel

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_Window

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_ProcessOutput

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_wxThread

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_wxTreeCtrl

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/GUI.Headers

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Intro_Page_Loader

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/MainFrame

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Process_Manager

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Project_File_Selection_Dialog

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Project_Folder_Lister

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Style_Loader

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/ToolBar_Initializer

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_Multi_DataPanel

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Project_Descriptions_Printer

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_Message_Dialog

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Help_Page_Constructor

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Dependency_Tree_Printer

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_Progress_Dialog

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Custom_wxDataViewTreeCtrl

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/GUI_List_Data_Recorder

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Project_File_Selection_Window

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/GUI.DEVELOPMENT/Workspace_Data_Holder



    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/DESCRIPTION.PROCESSING.SYSTEM/Description.Readers/Descriptor.File.Data.Collector

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/DESCRIPTION.PROCESSING.SYSTEM/Description.Readers/Descriptor.File.Reader

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/DESCRIPTION.PROCESSING.SYSTEM/Description.Readers/GUI.Descriptor.File.Reader

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/DESCRIPTION.PROCESSING.SYSTEM/Description.Readers/Descriptor.File.Syntax.Controller
    
    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/DESCRIPTION.PROCESSING.SYSTEM/Description.Readers/Record.Number.Determiner

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/DESCRIPTION.PROCESSING.SYSTEM/Description.Readers/Descriptor.File.Line.Reader


    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/BASIC.TOOLS/Cpp_FileOperations

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/BASIC.TOOLS/Custom_System_Interface

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/BASIC.TOOLS/DirectoryOperations

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/BASIC.TOOLS/IntToCharTranslater

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/BASIC.TOOLS/StringOperator

    ${CMAKE_CURRENT_SOURCE_DIR}/SOURCE/BASIC.TOOLS/Custom_System_Interface


    ${wxWidgets_BINARY_DIR}/lib/gcc_x64_lib/mswud

    ${wxWidgets_SOURCE_DIR}/include
)

target_link_directories(Pcynlitx PUBLIC

    ${CMAKE_CURRENT_SOURCE_DIR}/GUI.DEVELOPMENT

    ${wxWidgets_BINARY_DIR}/lib/gcc_x64_lib

    ${wxWidgets_SOURCE_DIR}/include
)

target_compile_options(Pcynlitx PUBLIC -std=c++17 -Wall -Bstatic

       -g -O0 -mthreads -D__WXMSW__ -D_UNICODE -DWIN32 )

target_link_options(Pcynlitx PUBLIC -static -mwindows)

