
#ifndef EVENT_ID_NUMBERS_H
#define EVENT_ID_NUMBERS_H

enum
{
  ID_Quit = 1,
  ID_OPEN_EMPTY_PROJECT_FILE = 2,
  ID_SHOW_AUTOR_INFO = 3,
  ID_INPUT_HEADER_FILE_LOCATION = 4,
  ID_INPUT_SOURCE_FILE_LOCATION = 5,
  ID_INPUT_LIBRARY_LOCATION = 6,
  ID_INPUT_LIBRARY_NAME = 7,
  ID_INPUT_CONSTRUCTION_POINT = 8,
  ID_INPUT_EXE_FILE_NAME = 9,
  ID_OPEN_INTROPAGE = 10,
  ID_INPUT_GIT_REPO_LOCATION = 11,
  ID_INPUT_MAIN_FILE_NAME = 12,
  ID_INPUT_C_STANDART = 13,
  ID_SELECT_PROJECT_FILE = 14,
  ID_SHOW_PROJECT_FILE = 15,
  ID_INPUT_OPTIONS = 16,
  ID_RUN_BUILD_SYSTEM_CONSTRUCTOR = 17,
  ID_PROCESS_END = 18,
  ID_SHOW_PROJECT_WAREHOUSE = 19,
  ID_FILE_SAVE = 20,
  ID_SHOW_DESCRIPTIONS =21,
  ID_OPEN_TREE_WIEW = 22,
  ID_RUN_EXECUTABLE_MAKEFILE_BUILDER = 23,
  ID_OPEN_TERMINAL = 24
};

#endif /* EVENT_ID_NUMBERS_H */
