
#ifndef EVENT_TABLE_HEADER_H
#define EVENT_TABLE_HEADER_H

#include "MainFrame.h"

BEGIN_EVENT_TABLE(MainFrame,wxFrame)
  EVT_MENU(ID_OPEN_TERMINAL,MainFrame::OpenTerminal)
  EVT_MENU(ID_INPUT_GIT_REPO_LOCATION,MainFrame::Enter_Git_Repo_Location)
  EVT_MENU(ID_INPUT_MAIN_FILE_NAME,MainFrame::Enter_Main_File_Name)
  EVT_MENU(ID_OPEN_EMPTY_PROJECT_FILE,MainFrame::Open_Empty_Project_File)
  EVT_MENU(ID_SELECT_PROJECT_FILE,MainFrame::Select_Project_File)
  EVT_MENU(ID_SHOW_PROJECT_FILE,MainFrame::Show_Project_File)
  EVT_MENU(ID_OPEN_INTROPAGE,MainFrame::Open_Intro_Page)
  EVT_MENU(ID_SHOW_AUTOR_INFO,MainFrame::Show_Author)
  EVT_MENU(ID_INPUT_HEADER_FILE_LOCATION,MainFrame::Enter_Header_File_Location)
  EVT_MENU(ID_INPUT_SOURCE_FILE_LOCATION,MainFrame::Enter_Source_File_Location)
  EVT_MENU(ID_INPUT_LIBRARY_LOCATION,MainFrame::Enter_Library_Location)
  EVT_MENU(ID_INPUT_LIBRARY_NAME,MainFrame::Enter_Library_Name)
  EVT_MENU(ID_INPUT_CONSTRUCTION_POINT,MainFrame::Enter_Warehouse_Location)
  EVT_MENU(ID_INPUT_EXE_FILE_NAME,MainFrame::Enter_Exe_File_Name)
  EVT_MENU(ID_INPUT_OPTIONS,MainFrame::Enter_Options)
  EVT_MENU(ID_INPUT_C_STANDART,MainFrame::Enter_Standard)
  EVT_MENU(ID_OPEN_TREE_WIEW,MainFrame::DirectoryOpen)
  EVT_MENU(ID_INCREASE_FONT_SIZE,MainFrame::Increase_Font_Size)
  EVT_MENU(ID_DECREASE_FONT_SIZE,MainFrame::Decrease_Font_Size)
  EVT_MENU(ID_UNDO_CHANGES,MainFrame::Undo_Changes)
  EVT_MENU(ID_REDO_CHANGES,MainFrame::Redo_Changes)
  EVT_MENU(ID_CLEAR_STYLE,MainFrame::Clear_Style)
  EVT_MENU(ID_RELOAD_STYLE,MainFrame::Reload_Default_Style)
  EVT_MENU(ID_SAVE_AS,MainFrame::Save_File_As)
  EVT_MENU(ID_CLEAR_TEXT,MainFrame::Clear_Text)
  EVT_MENU(ID_SET_CURSOR_TYPE_DEFAULT,MainFrame::Load_Default_Cursor)
  EVT_MENU(ID_CHANGE_CURSOR_TYPE,MainFrame::Change_Cursor_Type)
  EVT_MENU(ID_SET_CARET_LINE_VISIBLE,MainFrame::Set_Caret_Line_Visible)
  EVT_MENU(ID_SET_CARET_LINE_INVISIBLE,MainFrame::Set_Caret_Line_InVisible)
  EVT_MENU(ID_BOLD_STYLE,MainFrame::Use_Bold_Styling)
  EVT_MENU(ID_USE_BLOCK_CARET,MainFrame::Use_Block_Caret)
  EVT_MENU(ID_USE_DEFAULT_CARET,MainFrame::Use_Default_Caret)
  EVT_MENU(ID_FILE_SAVE,MainFrame::File_Save)
  EVT_MENU(ID_SAVE_AS,MainFrame::Save_File_As)
  EVT_MENU(ID_NEW_FILE,MainFrame::New_File)
  EVT_MENU(ID_OPEN_FILE,MainFrame::New_File)
  EVT_MENU(ID_FONT_CHANGE,MainFrame::Change_Font)
  EVT_MENU(ID_RUN_SINGLE_FILE_SCRIPT_CONSTRUCTOR,MainFrame::Single_File_Script_Construction)
  EVT_AUI_PANE_CLOSE(MainFrame::Close_Directory_Pane)
  EVT_MENU(ID_SHOW_PROJECT_WAREHOUSE,MainFrame::Show_Project_File)
  EVT_MENU(ID_RUN_BUILD_SYSTEM_CONSTRUCTOR,MainFrame::Start_Build_System_Construction)
  EVT_MENU(ID_PRINT_DESCRIPTIONS,MainFrame::PrintDescriptions)
  EVT_TREE_ITEM_ACTIVATED(wxID_ANY,MainFrame::FileSelect)
  EVT_TREE_BEGIN_LABEL_EDIT(wxID_ANY,MainFrame::FileNameEdit)
  EVT_PAINT(MainFrame::OnPaint)
END_EVENT_TABLE()

#endif /* EVENT_TABLE_HEADER_H */
